# INPUTS:
# ===================================================
# ipa_url (required): The URL to the decrypted YouTube IPA file. This should be a direct link to the IPA file.
# ===================================================

# OUTPUTS:
# ===================================================
# The decrypted YouTube IPA will be available in the GitHub Actions workspace's root directory.
# It will be available as "youtube.ipa".
# ===================================================

name: Prepare IPA
description: Downloads and validates decrypted IPA

inputs:
  ipa_url:
    required: true

runs:
  using: composite
  steps:
    - name: Download and validate IPA
      shell: bash
      run: |
        wget "${{ inputs.ipa_url }}" --no-verbose -O youtube.ipa
        file_type=$(file --mime-type -b youtube.ipa)
        if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
          echo "::error::Validation failed: Not a valid IPA. Detected: $file_type"
          exit 1
        fi
