# INPUTS:
# ===================================================
# repo: GitHub repository (owner/name), not the full URL
# output: Output filename (e.g. youpip.deb)
# ===================================================

# OUTPUTS:
# ===================================================
# The built deb package will be available in the root directory of the
# GitHub Action workspace with the specified output filename.
# ===================================================

name: Clone and Build
description: Clones a repo and builds a deb package using the Makefile

inputs:
  repo:
    description: GitHub repository (owner/name)
    required: true
  output:
    description: Output filename (e.g. youpip.deb)
    required: true

runs:
  using: composite
  steps:
    - name: Clone and Build
      shell: bash
      run: |
        git clone --quiet --depth=1 https://github.com/${{ inputs.repo }}.git
        REPO_NAME=$(basename ${{ inputs.repo }})
        cd "$REPO_NAME" && make package DEBUG=0 FINALPACKAGE=1
        mv packages/*.deb ../${{ inputs.output }}
