# .github/actions/setup-theos/action.yml
name: Setup Theos
description: Computes cache key, restores cache and installs Theos

runs:
  using: composite
  steps:
    - name: Compute Theos cache key
      shell: bash
      run: |
        echo "upstream_heads=$(git ls-remote https://github.com/theos/theos HEAD | cut -f1)-$(git ls-remote https://github.com/theos/sdks HEAD | cut -f1)" >> "$GITHUB_ENV"

    - name: Restore Theos cache
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/theos
        key: theos-${{ runner.os }}-${{ env.upstream_heads }}

    - name: Prepare Theos
      uses: Randomblock1/theos-action@v1
