name: Build YouTubeExtended (Reusable Workflow)

on:
  workflow_call:

jobs:
  build:
    name: Build YouTubeExtended Tweak
    runs-on: macos-latest

    steps:
      - name: Checkout YouTubeExtended source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

        # =================== DEPENDENCIES ===================
        # ====================================================
      - name: Compute Theos cache key
        shell: bash
        run: |
          echo "upstream_heads=$(git ls-remote https://github.com/theos/theos HEAD | cut -f1)-$(git ls-remote https://github.com/theos/sdks HEAD | cut -f1)" >> "$GITHUB_ENV"

      - name: Restore Theos cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: theos-${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1
        # ====================================================
        # ====================================================

        
        # =================== BUILD TWEAKS ===================
      - name: Build YouTube Extended Tweak (from source)
        shell: bash
        run: |
          set -e
          export FINALPACKAGE=1
          make clean package ROOTLESS=1
      
      - name: Upload built debs as artifacts in the current workflow run
        uses: actions/upload-artifact@v4
        with:
          name: built-debs
          path: packages/*.deb
          if-no-files-found: error
          retention-days: 1