name: Build YouTubeExtended (Reusable Workflow)

on:
  workflow_call:

jobs:
  build_tweaks:
    name: Build Tweaks
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        
        # =================== DEPENDENCIES ===================
        # ====================================================
      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ runner.os }}-${{ env.upstream_heads }}

      - name: Prepare Theos
        uses: Randomblock1/theos-action@v1
        # ====================================================
        # ====================================================

        
        # =================== BUILD TWEAKS ===================
      - name: Build YouTube Extended Tweak (from source)
        shell: bash
        run: |
          set -e
          export FINALPACKAGE=1
          make clean package ROOTLESS=1
      
      - name: Upload built debs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: built-debs
          path: packages/*.deb
          if-no-files-found: error
          retention-days: 1