# INPUTS
# ==================================================================
# - enable_youpip: boolean (required, default: false) - whether to build YouPiP
# - enable_ytuhd: boolean (required, default: false) - whether to build YouTubeUHD
# - enable_yq: boolean (required, default: false) - whether to build YouQuality
# - enable_ryd: boolean (required, default: false) - whether to build Return-YouTube-Dislikes
# - enable_ytabc: boolean (required, default: false) - whether to build YouTubeABConfig
# - enable_demc: boolean (required, default: false) - whether to build DontEatMyContent
# ==================================================================

# Produces the following debs:
# ==================================================================
# - youpip.deb (YouPiP tweak)
# - ytuhd.deb (YouTubeUHD tweak)
# - yq.deb (YouQuality tweak)
# - ryd.deb (Return-YouTube-Dislikes tweak)
# - ytabc.deb (YouTubeABConfig tweak)
# - demc.deb (DontEatMyContent tweak)
# All built debs will be stored in the root directory of the runner.
# ==================================================================

# OUTPUTS:
# ==================================================================
# This workflow provides the artifact "built-external-debs" within the current workflow run.
# This artifact can be downloaded by invoking the following action:
# ------------------------------------------------------------------
# - name: Download built external debs
#   uses: actions/download-artifact@v4
#   with:
#   name: built-external-debs
#   path: ${{ github.workspace }}
# ------------------------------------------------------------------
# ==================================================================

name: (INTERNAL) Build External Tweaks

on:
  workflow_call:
    inputs:
      enable_youpip:
        type: boolean
        required: true
        default: false

      enable_ytuhd:
        type: boolean
        required: true
        default: false

      enable_yq:
        type: boolean
        required: true
        default: false

      enable_ryd:
        type: boolean
        required: true
        default: false

      enable_ytabc:
        type: boolean
        required: true
        default: false

      enable_demc:
        type: boolean
        required: true
        default: false

jobs:
  build-external:
    name: Build external debs
    runs-on: macos-latest
    permissions:
      contents: read

    steps:
      # Only required to be able to use the Theos composite setup action
      - name: Checkout YouTubeExtended source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: .github/actions

      - name: Setup Theos
        uses: ./.github/actions/setup-theos

      # Dependency for all external tweaks
      - name: Setup YouTube Headers
        uses: ./.github/actions/setup-youtube-headers
        with:
          enable_demc: ${{ inputs.enable_demc }}

      # Dependency
      - name: Clone and Build YTVideoOverlay
        if: ${{ inputs.enable_yq || inputs.enable_youpip || inputs.enable_ytuhd }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/YTVideoOverlay
          output: ytvo.deb

      # Clone and build external tweaks if they've been enabled by the caller workflow.
      - name: Build YouPiP
        if: ${{ inputs.enable_youpip }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/YouPiP
          output: youpip.deb

      - name: Build YTUHD
        if: ${{ inputs.enable_ytuhd }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: Tonwalter888/YTUHD
          output: ytuhd.deb

      - name: Build Return-YouTube-Dislikes
        if: ${{ inputs.enable_ryd }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/Return-YouTube-Dislikes
          output: ryd.deb

      - name: Build YTABConfig
        if: ${{ inputs.enable_ytabc }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/YTABConfig
          output: ytabc.deb

      - name: Build YouGroupSettings
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/YouGroupSettings
          output: ygs.deb

      - name: Build YouQuality
        if: ${{ inputs.enable_yq }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: PoomSmart/YouQuality
          output: yq.deb

      - name: Build DontEatMyContent
        if: ${{ inputs.enable_demc }}
        uses: ./.github/actions/clone-and-build
        with:
          repo: therealFoxster/DontEatMyContent
          output: demc.deb

      - name: Clone Open in YouTube (Safari extension)
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/BillyCurtis/OpenYouTubeSafariExtension
          cd OpenYoutubeSafariExtension
          git sparse-checkout set --no-cone OpenYoutubeSafariExtension.appex
          git checkout
          mv *.appex ../

      - name: Upload built external debs
        uses: actions/upload-artifact@v4
        with:
          name: built-external-debs
          path: |
            *.deb
            *.appex
          if-no-files-found: error
          retention-days: 1
