name: Create YouTubeExtended app

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

      tweak_version:
        description: "Tweak version to include (Optional, must be a released version, e.g. 1.0.0)"
        default: ""
        required: false
        type: string

      enable_youpip:
        type: boolean
        required: true
        default: false

      enable_ytuhd:
        type: boolean
        required: true
        default: false

      enable_yq:
        type: boolean
        required: true
        default: false

      enable_ryd:
        type: boolean
        required: true
        default: false

      enable_ytabc:
        type: boolean
        required: true
        default: false

      enable_demc:
        type: boolean
        required: true
        default: false

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      ipa_url: ${{ github.event.inputs.ipa_url }}
      display_name: ${{ github.event.inputs.display_name }}
      bundle_id: ${{ github.event.inputs.bundle_id }}
      tweak_version: ${{ github.event.inputs.tweak_version }}
      enable_youpip: ${{ github.event.inputs.enable_youpip }}
      enable_ytuhd: ${{ github.event.inputs.enable_ytuhd }}
      enable_yq: ${{ github.event.inputs.enable_yq }}
      enable_ryd: ${{ github.event.inputs.enable_ryd }}
      enable_ytabc: ${{ github.event.inputs.enable_ytabc }}
      enable_demc: ${{ github.event.inputs.enable_demc }}