# PREREQUISITES:
# ==================================================================
# - The source code must be checked out before the following steps are invoked:
#   - Download debs
#   - Prepare IPA
#   - Get tweak version
#   - Get YouTube version
# ------------------------------------------------------------------
# - Those steps require access to the GitHub Actions:
# - .github/actions/download-debs
# - .github/actions/prepare-ipa
# - .github/actions/get-tweak-version
# - .github/actions/get-youtube-version
# ==================================================================

# OUTPUTS:
# ======================================================
# The YouTubeExtended IPA file will be uploaded as a draft release in the GitHub repository.
# ======================================================


# This workflow creates an IPA of YouTube with the selected tweaks included.
# It is triggered manually via the "Run workflow" button in the Actions tab of GitHub.
# ======================================================
# Note: The IPA file must be decrypted and accessible via a direct URL for this workflow to work.
# Suggested websites to upload the decrypted IPA:
# - https://catbox.moe/
# ======================================================
# To run this workflow locally, Docker and act can be used:

name: (USER) Create YouTubeExtended App

on:
  workflow_dispatch:
    inputs:
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      display_name:
        description: "App Name (Optional)"
        default: "YouTube"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtube"
        required: true
        type: string

      tweak_version:
        description: "YouTubeExtended tweak version (leave empty to use the latest version)"
        default: ""
        required: false
        type: choice
        options:
          - ""
          - "0.0.1"
          - "0.0.2"

      enable_youpip:
        description: "Include YouPIP tweak"
        default: false
        required: true
        type: boolean

      enable_ytuhd:
        description: "Include YouTubeUHD tweak"
        default: false
        required: true
        type: boolean

      enable_yq:
        description: "Include YouQuality tweak"
        default: false
        required: true
        type: boolean

      enable_ryd:
        description: "Include Return-YouTube-Dislikes tweak"
        default: false
        required: true
        type: boolean

      enable_ytabc:
        description: "Include YouTubeABConfig tweak"
        default: false
        required: true
        type: boolean

      enable_demc:
        description: "Include DontEatMyContent tweak"
        default: false
        required: true
        type: boolean

jobs:
  build:
    if: ${{ inputs.tweak_version == '' }}
    uses: ./.github/workflows/build.yml

  download_build:
    if: ${{ inputs.tweak_version != '' }}
    uses: ./.github/workflows/download_build.yml
    with:
      tweak_version: ${{ inputs.tweak_version }}

  build-external:
    if: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc }}
    uses: ./.github/workflows/build_external.yml
    with:
      enable_youpip: ${{ inputs.enable_youpip }}
      enable_ytuhd: ${{ inputs.enable_ytuhd }}
      enable_yq: ${{ inputs.enable_yq }}
      enable_ryd: ${{ inputs.enable_ryd }}
      enable_ytabc: ${{ inputs.enable_ytabc }}
      enable_demc: ${{ inputs.enable_demc }}

  package:
    name: Package IPA
    runs-on: macos-latest
    needs: [build, download_build, build-external]
    if: ${{ always() && (needs.build.result == 'success' || needs.download_build.result == 'success') && (needs.build-external.result == 'success' || needs.build-external.result == 'skipped') }}
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/actions
            control

      - name: Download debs
        uses: ./.github/actions/download-debs
        with:
          download_external: ${{ inputs.enable_youpip || inputs.enable_ytuhd || inputs.enable_yq || inputs.enable_ryd || inputs.enable_ytabc || inputs.enable_demc }}

      - name: Prepare IPA
        uses: ./.github/actions/prepare-ipa
        with:
          ipa_url: ${{ inputs.ipa_url }}

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

        # Version can be accessed as following:
        # Bare version: steps.version.outputs.version
        # Version as Git Tag: steps.version.outputs.tag
      - name: Get tweak version
        id: version
        uses: ./.github/actions/get-tweak-version

      - name: Get YouTube version
        id: yt_version
        uses: ./.github/actions/get-youtube-version

      - name: Generate YouTubeExtended filename
        id: filename
        run: echo "filename=YouTubeExtended-${{ steps.version.outputs.version }}_${{ steps.yt_version.outputs.version }}.ipa" >> $GITHUB_OUTPUT

      - name: Inject tweaks into IPA
        run: |
          EXTRA_FILES=("*.deb")
          if compgen -G "*.appex" > /dev/null; then
            EXTRA_FILES+=("*.appex")
          fi

          cyan -i youtube.ipa -o "${{ steps.filename.outputs.filename }}" -uwef "${EXTRA_FILES[@]}" -n "${{ github.event.inputs.display_name }}" -b ${{ github.event.inputs.bundle_id }}

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: YouTubeExtended-${{ github.run_number }}
          name: YouTubeExtended ${{ steps.version.outputs.version }} (YouTube ${{steps.yt_version.outputs.version}})
          files: ${{ steps.filename.outputs.filename }}
          draft: true
