# ======================================================
# This workflow is responsible for creating a GitHub Release when a new commit is pushed to the master branch.
# 1. Runs the build workflow to build the YouTubeExtended deb from source.
# 2. Downloads the built YouTubeExtended deb as artifact in the current workflow run.
# 3. Retrieves the version of the built tweak to use it as Git Tag and Release name.
# 4. Creates a Git Tag and a GitHub Release with the built deb attached as release asset.
# ======================================================

name: (INTERNAL) Create Release

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      # Only required to be able to use the composite actions in the repository.
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            .github/actions
            control

      - name: Download YouTubeExtended deb
        uses: ./.github/actions/download-debs
        with:
          download_external: false

      # Version can be accessed as following:
      # Bare version: steps.version.outputs.version
      # Version as Git Tag: steps.version.outputs.tag
      - name: Get tweak version
        id: version
        uses: ./.github/actions/get-tweak-version

      - name: Create release
        uses: ./.github/actions/tag-and-release
        with:
          tag: ${{ steps.version.outputs.tag }}

